version: "3"
services:
  db:
    container_name: project13_db
    image: postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project13
    # volumes:
    #   - ./data:/var/lib/postgresql/data
